#!/usr/bin/env /usr/bin/python3
"""Independent checks for NOTE.md.

Written from scratch, separately; verifies claims in NOTE.md that are
NOT already covered by audit/equivariance_checks.py, audit/wall_identity_check.py,
or that the verify/ suite states but does not certify. All exact, no floats
(one numeric-only sanity noted inline).

  N1. D is SQUAREFREE over Q: gcd(D, dD/da, dD/db, dD/dc) = 1.  (NOTE section 4
      labels this [COMPUTED] but no verify/ script certifies it; it is the
      load-bearing input to the S3 monodromy argument in section 5.)
  N2. D is irreducible over Q (sympy factor_list).
  N3. The covering cubic C = 2a r^3 - b r^2 + 2r - c is ABSOLUTELY irreducible
      as a polynomial (hence over C(a,b,c) as a cubic in r, by Gauss/primitivity):
      C is linear in c with content 1, so any factorization is trivial; certified
      here by sympy multivariate factorization + the primitivity checks the
      hand argument needs.
  N4. The y-eliminant is an IDENTITY: 2y^3 - 3F2 y^2 + 18F1 y
      + (27F1^2F3 - 18F1F2 + F2^3) == 0 in Q[x,y,z] -- valid at x=0 too,
      closing the denominator-clearing caveat of the resultant derivation.
  N5. Rigidity, re-derived without sp.solve: in the ansatz q = t + s*xy, the
      ideal generated by ALL nonconstant coefficients of det J has Groebner
      basis {t - 4, s - 3} over Q -- so (4,3) is the unique solution over C
      (not merely the unique one sympy's solver found), with multiplicity 1.
  N6. Specialization at (3/7, -2/5, 1/3) for the COVERING cubic C_q itself
      (verify/03 used the x-eliminant): irreducible over Q, discriminant a
      non-square rational => Galois group S3 over Q.
  N7. The det-1 rescaling G = diag(1/2,1/2,-1/2) o F o diag(1,2,2): integer
      coefficients, det JG == 1 identically, and G(0,1,0) == G(1,1,0) mod 2
      (the char-2 collision the note credits to deancureton/jacobian).
  N8. Escape arc: F(t, -1/t, 5/t^2) == (0, 2/t, 0); Siphon family verbatim;
      slowform333 reciprocal cubic -- independent re-derivations.
  N9. deg F = 7 (the note's "this map has degree 7").
  N10. Fiber over the origin = {(0,0,0)} exactly (the note: the origin is its
      own unique preimage).
"""
import sys
import sympy as sp
from sympy import Rational as R

x, y, z, a, b, c, r, t, s = sp.symbols('x y z a b c r t s')

F1 = (1 + x*y)**3 * z + y**2 * (1 + x*y) * (4 + 3*x*y)
F2 = y + 3*x*(1 + x*y)**2 * z + 3*x*y**2 * (4 + 3*x*y)
F3 = 2*x - 3*x**2*y - x**3*z
D = 27*a**2*c**2 - 18*a*b*c + 16*a + b**3*c - b**2
C = 2*a*r**3 - b*r**2 + 2*r - c

failures = []


def check(name, ok, detail=""):
    print(("PASS " if ok else "FAIL ") + name + (f"  [{detail}]" if detail else ""))
    if not ok:
        failures.append(name)


# ---------------------------------------------------------------- N1
g = D
for v in (a, b, c):
    g = sp.gcd(g, sp.diff(D, v))
check("N1 D squarefree: gcd(D, grad D) == 1 over Q  (=> squarefree over C, "
      "=> -4D nonsquare in C(a,b,c))", g == 1, f"gcd = {g}")

# ---------------------------------------------------------------- N2
fl = sp.factor_list(D)
check("N2 D irreducible over Q", len(fl[1]) == 1 and fl[1][0][1] == 1,
      f"factor_list = {fl}")

# ---------------------------------------------------------------- N3
flC = sp.factor_list(C)
irr4 = len(flC[1]) == 1 and flC[1][0][1] == 1
# hand argument ingredients: C = u*c + v with u = -1 (unit) -> irreducible in
# k[a,b,r][c] for ANY field k, in particular k = C; and primitive as a poly in
# r over C[a,b,c] (coefficient gcd 1):
cf = sp.Poly(C, r).all_coeffs()          # [2a, -b, 2, -c]
cont = sp.gcd(sp.gcd(cf[0], cf[1]), sp.gcd(cf[2], cf[3]))
check("N3 covering cubic absolutely irreducible (linear in c, unit c-coeff; "
      "primitive in r; sympy factor concurs)",
      irr4 and sp.Poly(C, c).all_coeffs()[0] == -1 and cont == 1,
      f"content = {cont}")

# ---------------------------------------------------------------- N4
Ey = 2*y**3 - 3*F2*y**2 + 18*F1*y + (27*F1**2*F3 - 18*F1*F2 + F2**3)
check("N4 y-eliminant identity holds in Q[x,y,z] (x=0 included; LC=2 constant "
      "=> y integral over C[a,b,c])", sp.expand(Ey) == 0)

# ---------------------------------------------------------------- N5
G1 = (1+x*y)**3*z + y**2*(1+x*y)*(t + s*x*y)
G2 = y + 3*x*(1+x*y)**2*z + 3*x*y**2*(t + s*x*y)
G3 = 2*x - 3*x**2*y - x**3*z
Jd = sp.expand(sp.Matrix([G1, G2, G3]).jacobian([x, y, z]).det())
pol = sp.Poly(Jd, x, y, z)
noncon = [cf for mono, cf in zip(pol.monoms(), pol.coeffs()) if mono != (0, 0, 0)]
GB = sp.groebner(noncon, t, s, order='lex')
check("N5 rigidity: ideal of nonconstant det-coeffs has GB {t-4, s-3} "
      "(unique C-point (4,3), multiplicity 1)",
      set(GB.exprs) == {t - 4, s - 3},
      f"#noncon = {len(noncon)}, GB = {list(GB.exprs)}")
check("N5 det at (t,s)=(4,3) equals -2", sp.expand(Jd.subs({t: 4, s: 3})) == -2)

# ---------------------------------------------------------------- N6
spec = {a: R(3, 7), b: R(-2, 5), c: R(1, 3)}
Cs = C.subs(spec)
flS = sp.factor_list(Cs)
irrS = len([f for f, m in flS[1] if f.free_symbols]) == 1 and \
       all(m == 1 for f, m in flS[1]) and sp.degree(flS[1][-1][0], r) == 3
d0 = sp.discriminant(sp.Poly(Cs, r))
check("N6 covering cubic at (3/7,-2/5,1/3): irreducible/Q, disc nonsquare "
      "=> S3 over Q", irrS and d0 != 0 and not sp.sqrt(d0).is_rational,
      f"disc = {d0}")
check("N6 disc equals -4*D at the specialization",
      sp.simplify(d0 + 4*D.subs(spec)) == 0)

# ---------------------------------------------------------------- N7
FF = sp.Matrix([F1, F2, F3])
pre = FF.subs({x: x, y: 2*y, z: 2*z}, simultaneous=True)
Gmap = sp.Matrix([pre[0]/2, pre[1]/2, -pre[2]/2])
Gexp = [sp.expand(gi) for gi in Gmap]
all_int = all(all(sp.Integer(co) == co and co == int(co)
                  for co in sp.Poly(gi, x, y, z).coeffs()) for gi in Gexp)
detG = sp.expand(sp.Matrix(Gexp).jacobian([x, y, z]).det())
p0 = [gi.subs({x: 0, y: 1, z: 0}) for gi in Gexp]
p1 = [gi.subs({x: 1, y: 1, z: 0}) for gi in Gexp]
diffs = [sp.nsimplify(u - v) for u, v in zip(p0, p1)]
check("N7 G = diag(1/2,1/2,-1/2) o F o diag(1,2,2): integer coeffs, det == 1, "
      "G(0,1,0) == G(1,1,0) mod 2",
      all_int and detG == 1 and all(d % 2 == 0 for d in diffs),
      f"diffs = {diffs}")

# ---------------------------------------------------------------- N8
arc = {x: t, y: -1/t, z: 5/t**2}
img = [sp.cancel(f.subs(arc)) for f in (F1, F2, F3)]
check("N8 escape arc F(t,-1/t,5/t^2) == (0, 2/t, 0)",
      img[0] == 0 and sp.cancel(img[1] - 2/t) == 0 and img[2] == 0)
okS = True
for p in [(0, 0, -1/(4*r**2)), (r, -3/(2*r), 13/(2*r**2)),
          (-r, 3/(2*r), 13/(2*r**2))]:
    im = [sp.cancel(sp.together(f.subs({x: p[0], y: p[1], z: p[2]})))
          for f in (F1, F2, F3)]
    okS &= (sp.cancel(im[0] + 1/(4*r**2)) == 0 and im[1] == 0 and im[2] == 0)
check("N8 Siphon family verbatim: three lambda_r-orbit points -> (-1/(4r^2),0,0)", okS)
vv = y + 1/x
num = sp.fraction(sp.together(F3*vv**3 - 2*vv**2 + F2*vv - 2*F1))[0]
check("N8 slowform333: F3 v^3 - 2v^2 + F2 v - 2F1 == 0 at v = y + 1/x",
      sp.expand(num) == 0)
check("N8 v == 1/r and reversed-cubic identity",
      sp.cancel(vv - (1 + x*y)/x) == 0 and
      sp.expand(-(C.subs(r, 1/sp.Symbol('v'))*sp.Symbol('v')**3)
                - (c*sp.Symbol('v')**3 - 2*sp.Symbol('v')**2
                   + b*sp.Symbol('v') - 2*a)) == 0)

# ---------------------------------------------------------------- N9
degs = [sp.Poly(f, x, y, z).total_degree() for f in (F1, F2, F3)]
check("N9 deg F = 7", max(degs) == 7, f"component degrees = {degs}")

# ---------------------------------------------------------------- N10
sols = sp.solve([F1, F2, F3], [x, y, z], dict=True)
check("N10 fiber over origin is exactly {(0,0,0)}",
      sols == [{x: 0, y: 0, z: 0}], f"sols = {sols}")

print()
if failures:
    print(f"RESULT: {len(failures)} FAILURE(S): {failures}")
    sys.exit(1)
print("RESULT: ALL NOTE-CHECKS PASS")
